In [20]:
## Data Collection
import nltk
nltk.download('gutenberg')
from nltk.corpus import gutenberg
import pandas as pd

data = gutenberg.raw('shakespeare-hamlet.txt')

with open('hamlet.txt','w') as file:
    file.write(data)

[nltk_data] Downloading package gutenberg to
[nltk_data]     C:\Users\vinay\AppData\Roaming\nltk_data...
[nltk_data]   Package gutenberg is already up-to-date!


In [21]:
import numpy as np
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from sklearn.model_selection import train_test_split

with open('hamlet.txt','r') as file:
    text = file.read().lower()

tokenizer = Tokenizer()
tokenizer.fit_on_texts([text])
total_words = len(tokenizer.word_index)+1
total_words

4818

In [22]:
tokenizer.word_index

{'the': 1,
 'and': 2,
 'to': 3,
 'of': 4,
 'i': 5,
 'you': 6,
 'a': 7,
 'my': 8,
 'it': 9,
 'in': 10,
 'that': 11,
 'ham': 12,
 'is': 13,
 'not': 14,
 'his': 15,
 'this': 16,
 'with': 17,
 'your': 18,
 'but': 19,
 'for': 20,
 'me': 21,
 'lord': 22,
 'as': 23,
 'what': 24,
 'he': 25,
 'be': 26,
 'so': 27,
 'him': 28,
 'haue': 29,
 'king': 30,
 'will': 31,
 'no': 32,
 'our': 33,
 'we': 34,
 'on': 35,
 'are': 36,
 'if': 37,
 'all': 38,
 'then': 39,
 'shall': 40,
 'by': 41,
 'thou': 42,
 'come': 43,
 'or': 44,
 'hamlet': 45,
 'good': 46,
 'do': 47,
 'hor': 48,
 'her': 49,
 'let': 50,
 'now': 51,
 'thy': 52,
 'how': 53,
 'more': 54,
 'they': 55,
 'from': 56,
 'enter': 57,
 'at': 58,
 'was': 59,
 'oh': 60,
 'like': 61,
 'most': 62,
 'there': 63,
 'well': 64,
 'know': 65,
 'selfe': 66,
 'would': 67,
 'them': 68,
 'loue': 69,
 'may': 70,
 "'tis": 71,
 'vs': 72,
 'sir': 73,
 'qu': 74,
 'which': 75,
 'did': 76,
 'why': 77,
 'laer': 78,
 'giue': 79,
 'thee': 80,
 'ile': 81,
 'must': 82,
 'hath': 

In [23]:
input_sequences = []
for line in text.split('\n'):
    tokken_list = tokenizer.texts_to_sequences([line])[0]
    print(tokken_list)
    for i in range(1,len(tokken_list)):
        n_gram_sequences = tokken_list[:i+1]
        input_sequences.append(n_gram_sequences)
        

[1, 687, 4, 45, 41, 1886, 1887, 1888]
[]
[]
[1180, 1889, 1890, 1891]
[]
[57, 407, 2, 1181, 177, 1892]
[]
[407, 1182, 63]
[408, 162, 377, 21, 247, 882]
[18, 66]
[]
[451, 224, 248, 1, 30]
[]
[408, 407]
[451, 25]
[]
[408, 6, 43, 62, 1893, 96, 18, 566]
[]
[451, 71, 51, 1894, 567, 378, 80, 3, 273, 1181]
[]
[408, 20, 16, 1895, 114, 379, 71, 883, 491]
[2, 5, 92, 688, 58, 144]
[]
[346, 29, 6, 108, 568, 884]
[408, 14, 7, 885, 1896]
[]
[346, 64, 380, 37, 6, 47, 689, 120, 2]
[347, 1, 1897, 4, 8, 257, 492, 68, 87, 149]
[57, 120, 2, 347]
[]
[408, 5, 117, 5, 139, 68, 247, 1182, 63]
[48, 205, 3, 16, 409]
[]
[140, 2, 1898, 348, 3, 1, 493]
[]
[408, 79, 6, 46, 124]
[]
[140, 125, 1899, 322, 1183, 121, 83, 1900, 6]
[1901, 407, 258, 8, 494, 79, 6, 380]
[]
[218, 408]
[]
[140, 1902, 407]
[]
[451, 94, 24, 13, 120, 63]
[48, 7, 495, 4, 28]
[]
[451, 236, 120, 236, 46, 347]
[]
[140, 24, 258, 16, 167, 886, 131, 3, 124]
[]
[451, 5, 29, 189, 153]
[]
[140, 120, 887, 71, 19, 33, 1184]
[2, 31, 14, 50, 1903, 136, 168, 4

In [24]:
input_sequences

[[1, 687],
 [1, 687, 4],
 [1, 687, 4, 45],
 [1, 687, 4, 45, 41],
 [1, 687, 4, 45, 41, 1886],
 [1, 687, 4, 45, 41, 1886, 1887],
 [1, 687, 4, 45, 41, 1886, 1887, 1888],
 [1180, 1889],
 [1180, 1889, 1890],
 [1180, 1889, 1890, 1891],
 [57, 407],
 [57, 407, 2],
 [57, 407, 2, 1181],
 [57, 407, 2, 1181, 177],
 [57, 407, 2, 1181, 177, 1892],
 [407, 1182],
 [407, 1182, 63],
 [408, 162],
 [408, 162, 377],
 [408, 162, 377, 21],
 [408, 162, 377, 21, 247],
 [408, 162, 377, 21, 247, 882],
 [18, 66],
 [451, 224],
 [451, 224, 248],
 [451, 224, 248, 1],
 [451, 224, 248, 1, 30],
 [408, 407],
 [451, 25],
 [408, 6],
 [408, 6, 43],
 [408, 6, 43, 62],
 [408, 6, 43, 62, 1893],
 [408, 6, 43, 62, 1893, 96],
 [408, 6, 43, 62, 1893, 96, 18],
 [408, 6, 43, 62, 1893, 96, 18, 566],
 [451, 71],
 [451, 71, 51],
 [451, 71, 51, 1894],
 [451, 71, 51, 1894, 567],
 [451, 71, 51, 1894, 567, 378],
 [451, 71, 51, 1894, 567, 378, 80],
 [451, 71, 51, 1894, 567, 378, 80, 3],
 [451, 71, 51, 1894, 567, 378, 80, 3, 273],
 [451, 71

In [25]:
## Pad sequence
max_sequence_len = max([len(x) for x in input_sequences])

In [26]:
input_sequences=np.array(pad_sequences(input_sequences,maxlen=max_sequence_len,padding='pre'))
input_sequences

array([[   0,    0,    0, ...,    0,    1,  687],
       [   0,    0,    0, ...,    1,  687,    4],
       [   0,    0,    0, ...,  687,    4,   45],
       ...,
       [   0,    0,    0, ...,    4,   45, 1047],
       [   0,    0,    0, ...,   45, 1047,    4],
       [   0,    0,    0, ..., 1047,    4,  193]], dtype=int32)

In [27]:
# Create predictors and labels

import tensorflow as tf
x,y=input_sequences[:,:-1],input_sequences[:,-1]
print(x)

[[   0    0    0 ...    0    0    1]
 [   0    0    0 ...    0    1  687]
 [   0    0    0 ...    1  687    4]
 ...
 [   0    0    0 ...  687    4   45]
 [   0    0    0 ...    4   45 1047]
 [   0    0    0 ...   45 1047    4]]


In [28]:
y

array([ 687,    4,   45, ..., 1047,    4,  193], dtype=int32)

In [29]:
y= tf.keras.utils.to_categorical(y,num_classes=total_words)
y

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [30]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)


In [31]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding,LSTM,Dense,Dropout


model = Sequential()
model.add(Embedding(total_words,100,input_length=max_sequence_len-1))
model.add(LSTM(150,return_sequences=True))
model.add(Dropout(0.2))
model.add(LSTM(100))
model.add(Dense(total_words,activation='softmax'))

model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])
model.summary()


Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_4 (LSTM)                   │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_2 (Dropout)             │ ?                      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_5 (LSTM)                   │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [32]:
history = model.fit(x_train,y_train,epochs=100,validation_data=(x_test,y_test),verbose=1)

Epoch 1/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 20s 24ms/step - accuracy: 0.0295 - loss: 7.1318 - val_accuracy: 0.0354 - val_loss: 6.7894
Epoch 2/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 14s 21ms/step - accuracy: 0.0377 - loss: 6.4356 - val_accuracy: 0.0387 - val_loss: 6.8974
Epoch 3/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 12s 19ms/step - accuracy: 0.0405 - loss: 6.3126 - val_accuracy: 0.0478 - val_loss: 6.9379
Epoch 4/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 13s 20ms/step - accuracy: 0.0506 - loss: 6.1727 - val_accuracy: 0.0486 - val_loss: 7.0027
Epoch 5/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 12s 18ms/step - accuracy: 0.0545 - loss: 6.0502 - val_accuracy: 0.0515 - val_loss: 7.0236
Epoch 6/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 12s 18ms/step - accuracy: 0.0597 - loss: 5.9510 - val_accuracy: 0.0552 - val_loss: 7.0890
Epoch 7/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 11s 18ms/step - accuracy: 0.0640 - loss: 5.8105 - val_accuracy: 0.0544 - val_loss: 7.1465
Epoch 8/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 11s 18ms/step - accuracy: 0.0699 - loss: 5

In [59]:
def predict_next_word(model,tokenizer,text,max_sequence_len):
    token_list = tokenizer.texts_to_sequences([text])[0]
    if len(token_list) >= max_sequence_len:
        token_list = token_list[-(max_sequence_len-1):]
    token_list = pad_sequences([token_list],maxlen=max_sequence_len-1,padding='pre')
    predicted = model.predict(token_list,verbose=0)
    predict_word_index = np.argmax(predicted,axis=1)
    for word,index in tokenizer.word_index.items():
        if index == predict_word_index:
            return word
    return None

In [52]:
input_text="Weird"
print(f"Input text:{input_text}")
max_sequence_len = model.input_shape[1]+1
next_word = predict_next_word(model,tokenizer,input_text,max_sequence_len)
print(f"Next word prediction :{next_word}")

Input text:Weird
Next word prediction :hamlet


In [57]:
model.save('next_word_lstm.h5')
import pickle
with open('tokenizer.pickle','wb') as handle:
    pickle.dump(tokenizer,handle,protocol=pickle.HIGHEST_PROTOCOL)

In [61]:
from tensorflow.keras.models import load_model
model1=load_model('next_word_lstm.h5')


In [62]:
input_text="Weird"
print(f"Input text:{input_text}")
max_sequence_len = model.input_shape[1]+1
next_word = predict_next_word(model1,tokenizer,input_text,max_sequence_len)
print(f"Next word prediction :{next_word}")

Input text:Weird
Next word prediction :hamlet
